server:
  port: ${PORT:8081}

spring:
  application:
    name: hack-backend

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: DEBUG
    com.hack: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.security: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate: DEBUG
    org.springframework.jdbc: DEBUG
